-- CREATE TABLE `clickon_detectleftusers_user_sessions`
-- (
--     `ID`                 int      NOT NULL,
--     `LAST_ACTIVITY_TIME` datetime NOT NULL,
--     `SESSION_START` datetime NOT NULL,
--     PRIMARY KEY (`ID`)
-- )