<?php

use \Bitrix\Main\DB;
use Bitrix\Main\EventManager;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\ModuleManager;
use Bitrix\Main\Config\Option;
use Bitrix\Main\Application;
use Bitrix\Main\IO\Directory;

Loc::loadMessages(__FILE__);

class clickon_pwa extends CModule {
    public $MODULE_ID = 'clickon.pwa';

    /** @var string[][]  */
    private $globalEvents;

    public function __construct() {
        $this->PARTNER_NAME = 'ClickON';
        $this->PARTNER_URI = 'https://www.clickon.ru/';
        $this->MODULE_NAME = GetMessage("CLICKON_PWA_MODULE_NAME");
        $this->MODULE_DESCRIPTION = GetMessage("CLICKON_PWA_MODULE_DESCRIPTION");


        $arModuleVersion = [];
        include(__DIR__ . "/version.php");

        if (is_array($arModuleVersion) && array_key_exists("VERSION", $arModuleVersion)) {
            $this->MODULE_VERSION = $arModuleVersion["VERSION"];
            $this->MODULE_VERSION_DATE = $arModuleVersion["VERSION_DATE"];
        }

        $this->globalEvents = [
            ['main', 'OnBeforeProlog', \ClickON\DetectLeftUsers\EventListener::class, 'onBeforePrologListener'],
        ];


    }


    // installation and uninstallation process

    function DoInstall() {
        $this->InstallEvents();
        $this->InstallFiles();
        $this->InstallDB();
        RegisterModule($this->MODULE_ID);
    }

    function DoUninstall() {
        global $APPLICATION;

        $this->UnInstallFiles();
        $this->UnInstallDB();
        $this->UnInstallEvents();

        ModuleManager::unRegisterModule($this->MODULE_ID);

        $APPLICATION->IncludeAdminFile(
            GetMessage("CLICKON_PWA_UNINSTALL_TITLE")." \"".GetMessage("CLICKON_PWA_MODULE_NAME")."\"",
            __DIR__."/unstep.php"
        );

        return false;
    }



    // install and uninstall Events

    public function InstallEvents(){

        EventManager::getInstance()->registerEventHandler(
            "main",
            "OnBeforeEndBufferContent",
            $this->MODULE_ID,
            "Clickon\Pwa",
            "appendScriptsToPage"
        );

        return false;
    }

    public function UnInstallEvents(){

        EventManager::getInstance()->unRegisterEventHandler(
            "main",
            "OnBeforeEndBufferContent",
            $this->MODULE_ID,
            "Clickon\Pwa",
            "appendScriptsToPage"
        );

        return false;
    }


    // install and uninstall Files

    function InstallFiles() {
        parent::InstallFiles(); // TODO: Change the autogenerated stub
        CopyDirFiles(
            __DIR__."/assets/scripts",
            Application::getDocumentRoot()."/".$this->MODULE_ID,
            true,
            true
        );

        CopyDirFiles(
            __DIR__."/assets/scripts/serviceWorker",
            Application::getDocumentRoot()."/",
            true,
            true
        );

        CopyDirFiles(
            __DIR__."/admin",
            Application::getDocumentRoot()."/bitrix/admin/".$this->MODULE_ID,
            true,
            true
        );

    }

    function UnInstallFiles() {
        parent::UnInstallFiles(); // TODO: Change the autogenerated stub

        Directory::deleteDirectory(
            Application::getDocumentRoot()."/".$this->MODULE_ID
        );

        Directory::deleteDirectory(
            Application::getDocumentRoot()."/manifest.json"
        );

        Directory::deleteDirectory(
            Application::getDocumentRoot()."/pwabuilder-sw.js"
        );

        Directory::deleteDirectory(
            Application::getDocumentRoot()."/admin/".$this->MODULE_ID
        );

        return false;
    }



    // install and uninstall Database

    public function InstallDB(){
        return false;
    }

    public function UnInstallDB(){
        Option::delete($this->MODULE_ID);
        return false;
    }




}